name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: azure-deployment # Aquí se especifica el environment
    steps:
    # Paso 1: Checkout del código
    - uses: actions/checkout@v3

    # Paso 2: Autenticación con Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ... otros pasos del pipeline